import java.text.SimpleDateFormat

plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.1'
    id 'maven-publish'
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact(tasks.shadowJar)
            artifactId = rootProject.name
        }
    }

    repositories {
        maven {
            name = "UtilityX-releases"
            url = uri("https://repo.utilityx.de/releases")

            credentials {
                username = System.getenv("REPOSILITE_USER")
                password = System.getenv("REPOSILITE_TOKEN")
            }
        }
    }
}

group = 'de.utilityx.core'

static def getTime() {
    SimpleDateFormat sdf = new SimpleDateFormat('yyMMdd-HHmm')
    sdf.setTimeZone(TimeZone.getTimeZone('UTC'))
    return sdf.format(new Date()).toString()
}

String shortVersion = null
if (hasProperty('ver')) {
    if (ver.charAt(0) == 'v') {
        shortVersion = ver.substring(1).toUpperCase()
    } else {
        shortVersion = ver.toUpperCase()
    }
}

int rcIdx
if (shortVersion == null || shortVersion == '') {
    version = getTime() + '-SNAPSHOT'
} else if ((rcIdx = shortVersion.indexOf('-RC-')) != -1) {
    version = shortVersion.substring(0, rcIdx) + '-SNAPSHOT'
} else {
    version = shortVersion
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    implementation 'studio.mevera:imperat-core:2.2.1'
    implementation 'studio.mevera:imperat-bukkit:2.2.1'
    implementation 'com.github.Mqzn:Lotus:1.6.0'
    implementation 'io.papermc:paperlib:1.0.8'
}

shadowJar {
    archiveClassifier.set('')
    relocate 'io.papermc.lib', 'shadow.io.papermc.paperlib'
    minimize()
}

jar.enabled = false
assemble.dependsOn(shadowJar)
